### ISSUE TITLE
Use it in .yml

### ISSUE THREAD

**Issue by xFabifont** [Tob1asDocker/rpi-certbot#1]
Hi, how can i use it in docker-compose.yml ?

**Comment by Tob1as** [comment]
Hi, example:

```yml
certbot:
  image: tobi312/rpi-certbot:latest
  command:  bash -c "sleep 6 && certbot certonly --standalone -d __YOUR-DOMAIN__ -d www.__YOUR-DOMAIN__ --email __YOUR-EMAIL__ --text --agree-tos --server https://acme-v01.api.letsencrypt.org/directory --rsa-key-size 4096 --verbose --renew-by-default --standalone-supported-challenges http-01"
  entrypoint: ""
  #ports:
  #  - "80:80"
  #  - "443:443"
  volumes:
    - ./certbot:/etc/letsencrypt
```

or see in this [Repository](https://github.com/Tob1asDocker/docker-compose/blob/master/rpi-webgis/docker-compose.yml).

Note: However, the container stops with the example command after it has been executed. Maybe it helps to make a bow around it: 
``` 
while : ; do CERTBOT-COMMAND-HERE; sleep 2628000; done 
```
